[project]
name = "lab-infrastructure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncssh>=2.21.0",
    "ipdb>=0.13.13",
]
